### ISSUE TITLE
The KL loss becomes negative during training

### ISSUE THREAD

**Issue by isunLt** [Eaphan/OLIVINE#1]
I just clone the project, download the mask from google drive and prepare the evironment following the requirement. However, the KL loss becomes negative during training. Could the authors kindly help me with this issue?
![1](https://github.com/user-attachments/assets/983da892-bab6-4196-8375-9acebdae0c05)

**Comment by Eaphan** [comment]
Keep it easy, it's a normal phenomenon.

**Comment by isunLt** [comment]
> Keep it easy, it's a normal phenomenon.

Thank you for the quick reply. In this case I will just keep running the code.
